name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Exécute les tests pour les pushs sur la branche principale
      - '**'  # Ou remplacez par d'autres branches spécifiques si nécessaire

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Remplacez par la version appropriée

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

      # Exécution des tests
      - name: Run Pytest
        run: pytest
